#!/bin/bash

HERE=$(dirname $(readlink -f $0))
SCREEN_SIZE=`xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/'`
XDISPLAY=:1
LOG_LEVEL=${LOG_LEVEL:-INFO}
if [[ -z $PYTHON ]]; then
    PYTHON=python3
fi

Xephyr +extension RANDR -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
XEPHYR_PID=$!
(
  sleep 1
  env DISPLAY=${XDISPLAY} ${PYTHON} "${HERE}"/../bin/lavinder -l ${LOG_LEVEL} $@ &
  LAVINDER_PID=$!
  env DISPLAY=${XDISPLAY} xterm &
  wait $LAVINDER_PID
  kill $XEPHYR_PID
)
